parent=keycloak.v2
import=common/keycloak

stylesCommon=vendor/patternfly-v5/patternfly.min.css vendor/patternfly-v5/patternfly-addons.css
styles=css/styles.css css/nadigit-brand.css

darkMode=false

# Realm setting: Theme → Login theme → nadigit-ims
