// permissions.config.ts
export const PermissionsConfig = {
    PRODUCTS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: true,
            read: true,
            update: true,
            delete: false,
        },
        VENDOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
    },
    CATEGORIES: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            products_read: true,
        },
        WAREHOUSEMAN: {
            create: true,
            read: true,
            update: true,
            delete: false,
            products_read: true,
        },
        VENDOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            products_read: true,
        },
    },
    CUSTOMERS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            history_read: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
            history_read: false,
        },
        VENDOR: {
            create: true,
            read: true,
            update: true,
            delete: false,
            history_read: true,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            history_read: true,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            history_read: true,
        },
    },
    ORDERS: {
        ADMIN: {
            create: true,
            read: true,
            process:true,
            update: true,
            delete: true,
            cancel: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            process:false,
            update: false,
            delete: false,
            cancel: false,
        },
        VENDOR: {
            create: true,
            read: true,
            process:true,
            update: true,
            delete: false,
            cancel: true,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            cancel: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            cancel: false,
        },
        
    },
    RETURNS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            process: true,
            cancel: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
        VENDOR: {
            create: true,
            read: true,
            update: true,
            delete: false,
            process: true,
            cancel: true,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
    },
    PROFILE: {
        ADMIN: {
            create: false,
            read: true,
            update: true,
            delete: false,
        },
        WAREHOUSEMAN: {
            create: false,
            read: true,
            update: true,
            delete: false,
        },
        VENDOR: {
            create: false,
            read: true,
            update: true,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: true,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: true,
            delete: false,
        },
    },
    SETTINGS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: false,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        VENDOR: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
    },
    SHOPS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            cash_read: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
            cash_read: true,
        },
        VENDOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            cash_read: true,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
    },
    SUPPLIERS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: true,
            read: true,
            update: true,
            delete: false,
        },
        VENDOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
    },
    USERS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        VENDOR: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
    },
    WAREHOUSES: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        VENDOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        
    },
    PURCHASES: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            process: true,
            cancel: true,
        },
        WAREHOUSEMAN: {
            create: true,
            read: true,
            update: true,
            delete: false,
            process: true,
            cancel: true,
        },
        VENDOR: {
            create: true,
            read: true,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
    },
    EXPENSES: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: true,
            read: true,
            update: true,
            delete: false,
        },
        VENDOR: {
            create: true,
            read: true,
            update: true,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
    },
    PAYMENTS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            confirm: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
            confirm: false,
        },
        VENDOR: {
            create: true,
            read: true,
            update: true,
            delete: false,
            confirm: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            confirm: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            confirm: false,
        },
    },
    REFUNDS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        VENDOR: {
            create: true,
            read: true,
            update: true,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
    },
    FINANCIAL_DOCUMENTS:
        {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            issue: true,
            cancel: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
            issue: false,
            cancel: false,
        },
        VENDOR: {
            create: true,
            read: true,
            update: false,
            delete: false,
            issue: false,
            cancel: false,
        },
        AUDITOR: {
            create: true,
            read: true,
            update: false,
            delete: false,
            issue: false,
            cancel: false,
        },
        ACCOUNTANT: {
            create: true,
            read: true,
            update: true,
            delete: true,
            issue: true,
            cancel: true,
        },
    }
};
