// permissions.config.ts
export const PermissionsConfig = {
    PRODUCTS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            archive: true,
        },
        WAREHOUSEMAN: {
            create: true,
            read: true,
            update: true,
            delete: false,
            archive: true,
        },
        VENDOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            archive: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            archive: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            archive: false,
        },
        CASHIER: {
            create: false,
            read: true,
            update: false,
            delete: false,
            archive: false,
            products_read: true,
        },
    },
    CATEGORIES: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            products_read: true,
        },
        WAREHOUSEMAN: {
            create: true,
            read: true,
            update: true,
            delete: false,
            products_read: true,
        },
        VENDOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            products_read: true,
        },
        CASHIER: {
            create: false,
            read: true,
            update: false,
            delete: false,
            products_read: true,
        },
    },
    CUSTOMERS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            history_read: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
            history_read: false,
        },
        VENDOR: {
            create: true,
            read: true,
            update: true,
            delete: false,
            history_read: true,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            history_read: true,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            history_read: true,
        },
        CASHIER: {
            create: true,
            read: true,
            update: false,
            delete: false,
            history_read: false,
        },
    },
    ORDERS: {
        ADMIN: {
            create: true,
            read: true,
            process:true,
            update: true,
            delete: true,
            cancel: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            process:false,
            update: false,
            delete: false,
            cancel: false,
        },
        VENDOR: {
            create: true,
            read: true,
            process:true,
            update: true,
            delete: false,
            cancel: true,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            cancel: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            cancel: false,
        },
        CASHIER: {
            create: true,
            read: true,
            process: true,
            update: true,
            delete: false,
            cancel: false,
        },
    },
    STOCK_MOVEMENTS: {
        ADMIN: {
            read: true,
        },
        WAREHOUSEMAN: {
            read: true,
        },
        VENDOR: {
            read: true,
        },
        AUDITOR: {
            read: true,
        },
        ACCOUNTANT: {
            read: true,
        },
    },
    WAREHOUSE_TRANSFERS: {
        ADMIN: {
            read: true,
            create: true,
            update: true,
            delete: true,
            process: true,
            cancel: true,
        },
        WAREHOUSEMAN: {
            read: true,
            create: true,
            update: true,
            delete: false,
            process: false,
            cancel: false,
        },
        VENDOR: {
            read: true,
            create: false,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
        AUDITOR: {
            read: true,
            create: false,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
        ACCOUNTANT: {
            read: true,
            create: false,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
    },
    RETURNS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            process: true,
            cancel: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
        VENDOR: {
            create: true,
            read: true,
            update: true,
            delete: false,
            process: true,
            cancel: true,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
    },
    PROFILE: {
        ADMIN: {
            create: false,
            read: true,
            update: true,
            delete: false,
        },
        WAREHOUSEMAN: {
            create: false,
            read: true,
            update: true,
            delete: false,
        },
        VENDOR: {
            create: false,
            read: true,
            update: true,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: true,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: true,
            delete: false,
        },
        CASHIER: {
            create: false,
            read: true,
            update: true,
            delete: false,
        },
    },
    SETTINGS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: false,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        VENDOR: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
    },
    SHOPS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            cash_read: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
            cash_read: true,
        },
        VENDOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            cash_read: true,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        CASHIER: {
            create: false,
            read: true,
            update: false,
            delete: false,
            cash_read: true,
        },
    },
    SUPPLIERS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: true,
            read: true,
            update: true,
            delete: false,
        },
        VENDOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
    },
    USERS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        VENDOR: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
    },
    WAREHOUSES: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        VENDOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        
    },
    PURCHASES: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            process: true,
            cancel: true,
        },
        WAREHOUSEMAN: {
            create: true,
            read: true,
            update: true,
            delete: false,
            process: true,
            cancel: true,
        },
        VENDOR: {
            create: true,
            read: true,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
    },
    EXPENSES: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: true,
            read: true,
            update: true,
            delete: false,
        },
        VENDOR: {
            create: true,
            read: true,
            update: true,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
    },
    PAYMENTS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            confirm: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
            confirm: false,
        },
        VENDOR: {
            create: true,
            read: true,
            update: true,
            delete: false,
            confirm: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            confirm: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            confirm: false,
        },
    },
    REFUNDS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        VENDOR: {
            create: true,
            read: true,
            update: true,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
    },
    FINANCIAL_DOCUMENTS:
        {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            issue: true,
            cancel: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
            issue: false,
            cancel: false,
        },
        VENDOR: {
            create: true,
            read: true,
            update: false,
            delete: false,
            issue: false,
            cancel: false,
        },
        AUDITOR: {
            create: true,
            read: true,
            update: false,
            delete: false,
            issue: false,
            cancel: false,
        },
        ACCOUNTANT: {
            create: true,
            read: true,
            update: true,
            delete: true,
            issue: true,
            cancel: true,
        },
    },
    BANK_ACCOUNTS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        VENDOR: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
    },
    BANKS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        VENDOR: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
    },
    PURCHASE_RETURNS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            process: true,
            cancel: true,
        },
        WAREHOUSEMAN: {
            create: true,
            read: true,
            update: true,
            delete: false,
            process: true,
            cancel: true,
        },
        VENDOR: {
            create: true,
            read: true,
            update: true,
            delete: false,
            process: true,
            cancel: true,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            process: false,
            cancel: false,
        },
    },
    PURCHASE_CREDITS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
        },
        VENDOR: {
            create: true,
            read: true,
            update: true,
            delete: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
        },
    },
    CUSTOMER_CREDITS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            issue: true,
            adjust: true,
            set_limit: true,
            change_status: true,
            reverse_transaction: true,
        },
        WAREHOUSEMAN: {
            create: false,
            read: false,
            update: false,
            delete: false,
            issue: false,
            adjust: false,
            set_limit: false,
            change_status: false,
            reverse_transaction: false,
        },
        VENDOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            issue: false,
            adjust: false,
            set_limit: false,
            change_status: false,
            reverse_transaction: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            issue: false,
            adjust: false,
            set_limit: false,
            change_status: false,
            reverse_transaction: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            issue: false,
            adjust: false,
            set_limit: false,
            change_status: false,
            reverse_transaction: false,
        },
        CASHIER: {
            create: false,
            read: false,
            update: false,
            delete: false,
            issue: false,
            adjust: false,
            set_limit: false,
            change_status: false,
            reverse_transaction: false,
        },
    },
    POS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: false,
            process: true,
        },
        VENDOR: {
            create: true,
            read: true,
            update: true,
            delete: false,
            process: true,
        },
        CASHIER: {
            create: true,
            read: true,
            update: true,
            delete: false,
            process: true,
        },
    },
    INVENTORY_WRITE_OFFS: {
        ADMIN: {
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
        },
        WAREHOUSEMAN: {
            create: true,
            read: true,
            update: true,
            delete: false,
            approve: true,
            reject: true,
        },
        VENDOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
        },
        AUDITOR: {
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
        },
        ACCOUNTANT: {
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
        },
    },
};
