import * as FileSaver from 'file-saver';
import { BRAND_COLORS } from './brand-colors';
import { BRAND_ASSETS } from './brand-assets';

export interface Column {
    field: string;
    header: string;
    customExportHeader?: string;
}

export interface ExportColumn {
    title: string;
    dataKey: string;
}

export class ReportingService {

    private logoDataUrlPromise?: Promise<string | null>;

    exportPdf(exportColumns, object, type, title?: string) {
        Promise.all([
            import('jspdf'),
            import('jspdf-autotable'),
            this.loadLogoDataUrl(),
          ]).then(([jsPDF, autoTable, logoDataUrl]) => {
            const doc = new jsPDF.default('p', 'px', 'a4');
            let PDF_EXTENSION = '.pdf';
            const pageWidth = doc.internal.pageSize.getWidth();
            const pageHeight = doc.internal.pageSize.getHeight();
            const marginX = 40;
            let startY = 30;

            // Brand header — marketing logo when available
            const logoHeight = 28;
            const logoWidth = logoHeight * (1500 / 550);
            if (logoDataUrl) {
              doc.addImage(logoDataUrl, 'PNG', marginX, 8, logoWidth, logoHeight);
            } else {
              doc.setFontSize(11);
              doc.setTextColor(BRAND_COLORS.navy);
              doc.setFont(undefined, 'bold');
              doc.text('Nadigit IMS', marginX, 18);
            }

            doc.setFontSize(8);
            doc.setFont(undefined, 'normal');
            doc.setTextColor(BRAND_COLORS.textSecondary);
            doc.text('ims.nadigit.com', pageWidth - marginX, 18, { align: 'right' });

            doc.setDrawColor(BRAND_COLORS.saas);
            doc.setLineWidth(1.5);
            doc.line(marginX, 40, pageWidth - marginX, 40);
            startY = 52;

            if (title) {
              doc.setFontSize(14);
              doc.setFont(undefined, 'bold');
              doc.setTextColor(BRAND_COLORS.navy);
              const textWidth = doc.getTextWidth(title);
              const xPosition = (pageWidth - textWidth) / 2;
              doc.text(title, xPosition, startY);
              startY += 16;
            }

            autoTable.default(doc, {
                columns: exportColumns,
                body: object,
                startY,
                margin: { top: startY, left: marginX, right: marginX },
                headStyles: {
                    fillColor: [11, 31, 74],
                    textColor: [255, 255, 255],
                    fontStyle: 'bold',
                },
                alternateRowStyles: {
                    fillColor: [245, 247, 251],
                },
                styles: {
                    textColor: [26, 31, 54],
                    lineColor: [220, 227, 240],
                    lineWidth: 0.5,
                },
                didDrawPage: () => {
                    const footerY = pageHeight - 16;
                    doc.setFontSize(8);
                    doc.setTextColor(BRAND_COLORS.textSecondary);
                    doc.text('Generated by Nadigit IMS', marginX, footerY);
                    doc.text(
                        new Date().toLocaleString(),
                        pageWidth - marginX,
                        footerY,
                        { align: 'right' }
                    );
                },
            });

            doc.save(type + new Date().getTime() + PDF_EXTENSION);
          });
    }

    private loadLogoDataUrl(): Promise<string | null> {
        if (!this.logoDataUrlPromise) {
            this.logoDataUrlPromise = fetch(BRAND_ASSETS.logoLightPng)
                .then((response) => (response.ok ? response.blob() : null))
                .then((blob) => {
                    if (!blob) {
                        return null;
                    }
                    return new Promise<string>((resolve, reject) => {
                        const reader = new FileReader();
                        reader.onloadend = () => resolve(String(reader.result));
                        reader.onerror = () => reject(reader.error);
                        reader.readAsDataURL(blob);
                    });
                })
                .catch(() => null);
        }
        return this.logoDataUrlPromise;
    }

    getObjectType<T>(arr: T[]): T {
        return {} as T;
      }

    exportExcel(object, type) {
        import('xlsx').then((xlsx) => {
            console.log(object);
            if (Array.isArray(object)) {
                const elementType = typeof object[0];
                console.log(object[0]);
                console.log(elementType);
              }
            const worksheet = xlsx.utils.json_to_sheet(object);
            const workbook = { Sheets: { data: worksheet }, SheetNames: ['data'] };
            const excelBuffer: any = xlsx.write(workbook, { bookType: 'xlsx', type: 'array' });
            this.saveAsExcelFile(excelBuffer, type);
        });
    }

    saveAsExcelFile(buffer: any, fileName: string): void {
        let EXCEL_TYPE = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8';
        let EXCEL_EXTENSION = '.xlsx';
        const data: Blob = new Blob([buffer], {
            type: EXCEL_TYPE
        });
        FileSaver.saveAs(data, fileName + '_export_' + new Date().getTime() + EXCEL_EXTENSION);
    }

}
