import * as FileSaver from 'file-saver';
import { BRAND_COLORS } from './brand-colors';
import { BRAND_ASSETS } from './brand-assets';

export interface Column {
    field: string;
    header: string;
    customExportHeader?: string;
}

export interface ExportColumn {
    title: string;
    dataKey: string;
}

/**
 * The block that identifies an exported document: who produced it, what it is, and when.
 *
 * Every string arrives already translated. The service cannot translate them itself: callers
 * switch to the organization's locale, export, and switch straight back, so anything this class
 * resolved asynchronously would read the locale that had already been restored.
 */
export interface ExportDocumentHeader {
    /** What the report is, in the organization's locale. */
    title: string;
    organizationName?: string;
    /** e.g. the active filter or date range, so a saved file still explains itself. */
    subtitle?: string;
    /** Translated label for the generation timestamp, e.g. "Généré le". */
    generatedLabel?: string;
    generatedAt?: string;
}

export class ReportingService {

    private logoDataUrlPromise?: Promise<string | null>;

    exportPdf(exportColumns, object, type, title?: string, organizationName?: string) {
        Promise.all([
            import('jspdf'),
            import('jspdf-autotable'),
            this.loadLogoDataUrl(),
          ]).then(([jsPDF, autoTable, logoDataUrl]) => {
            const doc = new jsPDF.default('p', 'px', 'a4');
            let PDF_EXTENSION = '.pdf';
            const pageWidth = doc.internal.pageSize.getWidth();
            const pageHeight = doc.internal.pageSize.getHeight();
            const marginX = 40;
            let startY = 30;

            // Brand header — marketing logo when available
            const logoHeight = 28;
            const logoWidth = logoHeight * (1500 / 550);
            if (logoDataUrl) {
              doc.addImage(logoDataUrl, 'PNG', marginX, 8, logoWidth, logoHeight);
            } else {
              doc.setFontSize(11);
              doc.setTextColor(BRAND_COLORS.navy);
              doc.setFont(undefined, 'bold');
              doc.text('Nadigit IMS', marginX, 18);
            }

            doc.setFontSize(8);
            doc.setFont(undefined, 'normal');
            doc.setTextColor(BRAND_COLORS.textSecondary);
            doc.text('ims.nadigit.com', pageWidth - marginX, 18, { align: 'right' });

            doc.setDrawColor(BRAND_COLORS.saas);
            doc.setLineWidth(1.5);
            doc.line(marginX, 40, pageWidth - marginX, 40);
            startY = 52;

            if (title) {
              doc.setFontSize(14);
              doc.setFont(undefined, 'bold');
              doc.setTextColor(BRAND_COLORS.navy);
              const textWidth = doc.getTextWidth(title);
              const xPosition = (pageWidth - textWidth) / 2;
              doc.text(title, xPosition, startY);
              startY += 16;
            }

            // Whose report this is. The band above carries Nadigit's mark because we made the
            // software; the organization name says who the figures belong to, which is what
            // matters to whoever opens the file.
            if (organizationName) {
              doc.setFontSize(9);
              doc.setFont(undefined, 'normal');
              doc.setTextColor(BRAND_COLORS.textSecondary);
              const orgWidth = doc.getTextWidth(organizationName);
              doc.text(organizationName, (pageWidth - orgWidth) / 2, startY);
              startY += 14;
            }

            autoTable.default(doc, {
                columns: exportColumns,
                body: object,
                startY,
                margin: { top: startY, left: marginX, right: marginX },
                headStyles: {
                    fillColor: [11, 31, 74],
                    textColor: [255, 255, 255],
                    fontStyle: 'bold',
                },
                alternateRowStyles: {
                    fillColor: [245, 247, 251],
                },
                styles: {
                    textColor: [26, 31, 54],
                    lineColor: [220, 227, 240],
                    lineWidth: 0.5,
                },
                didDrawPage: () => {
                    const footerY = pageHeight - 16;
                    doc.setFontSize(8);
                    doc.setTextColor(BRAND_COLORS.textSecondary);
                    doc.text('Generated by Nadigit IMS', marginX, footerY);
                    doc.text(
                        new Date().toLocaleString(),
                        pageWidth - marginX,
                        footerY,
                        { align: 'right' }
                    );
                },
            });

            doc.save(type + new Date().getTime() + PDF_EXTENSION);
          });
    }

    private loadLogoDataUrl(): Promise<string | null> {
        if (!this.logoDataUrlPromise) {
            this.logoDataUrlPromise = fetch(BRAND_ASSETS.logoLightPng)
                .then((response) => (response.ok ? response.blob() : null))
                .then((blob) => {
                    if (!blob) {
                        return null;
                    }
                    return new Promise<string>((resolve, reject) => {
                        const reader = new FileReader();
                        reader.onloadend = () => resolve(String(reader.result));
                        reader.onerror = () => reject(reader.error);
                        reader.readAsDataURL(blob);
                    });
                })
                .catch(() => null);
        }
        return this.logoDataUrlPromise;
    }

    getObjectType<T>(arr: T[]): T {
        return {} as T;
      }

    /**
     * @param header identifies the document. Without it the sheet opens straight onto a grid of
     *        numbers with nothing saying what it is or who produced it — which is what a saved and
     *        emailed file looks like a week later.
     */
    exportExcel(object, type, header?: ExportDocumentHeader) {
        import('xlsx').then((xlsx) => {
            const resolved = header ?? { title: this.prettifyType(type) };
            const headerRows: string[][] = [];

            if (resolved.organizationName) {
                headerRows.push([resolved.organizationName]);
            }
            headerRows.push([resolved.title]);
            if (resolved.subtitle) {
                headerRows.push([resolved.subtitle]);
            }
            if (resolved.generatedAt) {
                headerRows.push([
                    resolved.generatedLabel ? `${resolved.generatedLabel} ${resolved.generatedAt}`
                                            : resolved.generatedAt,
                ]);
            }
            // A cell holding an empty string, not an empty array: aoa_to_sheet drops a trailing
            // empty row entirely, which put the table header straight under the date line.
            headerRows.push(['']);

            const worksheet = xlsx.utils.aoa_to_sheet(headerRows);
            // The table's own header row is written by json_to_sheet's key inspection; callers
            // translate those keys before calling, so it lands in the organization's locale.
            xlsx.utils.sheet_add_json(worksheet, object, { origin: -1 });

            worksheet['!cols'] = this.columnWidths(object);
            // Let the title breathe across the table rather than being clipped at column A.
            const span = Math.max(1, this.columnCount(object));
            worksheet['!merges'] = headerRows
                .map((row, index) => (row.length === 1
                    ? { s: { r: index, c: 0 }, e: { r: index, c: span - 1 } }
                    : null))
                .filter((merge): merge is any => merge !== null);

            const workbook = { Sheets: { data: worksheet }, SheetNames: ['data'] };
            const excelBuffer: any = xlsx.write(workbook, { bookType: 'xlsx', type: 'array' });
            this.saveAsExcelFile(excelBuffer, type);
        });
    }

    /** Last-resort title when a caller has not been given one yet: "stock-movements" -> "Stock Movements". */
    private prettifyType(type: string): string {
        return (type || 'export')
            .replace(/[-_]+/g, ' ')
            .replace(/\b\w/g, (c) => c.toUpperCase());
    }

    private columnCount(object: any): number {
        return Array.isArray(object) && object.length > 0 ? Object.keys(object[0]).length : 1;
    }

    /** Roughly fit each column to its widest cell, capped so one long note cannot swallow the sheet. */
    private columnWidths(object: any): { wch: number }[] {
        if (!Array.isArray(object) || object.length === 0) {
            return [];
        }
        return Object.keys(object[0]).map((key) => {
            const widest = object.reduce((max: number, row: any) => {
                const value = row?.[key];
                return Math.max(max, value == null ? 0 : String(value).length);
            }, String(key).length);
            return { wch: Math.min(48, Math.max(10, widest + 2)) };
        });
    }

    saveAsExcelFile(buffer: any, fileName: string): void {
        let EXCEL_TYPE = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8';
        let EXCEL_EXTENSION = '.xlsx';
        const data: Blob = new Blob([buffer], {
            type: EXCEL_TYPE
        });
        FileSaver.saveAs(data, fileName + '_export_' + new Date().getTime() + EXCEL_EXTENSION);
    }

}
